# Generated by Django 6.0 on 2025-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('source', models.CharField(default='user-upload', help_text="Where this document came from (e.g., 'upload').", max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
