# Generated by Django 6.0 on 2025-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmate_app', '0003_habit_pomodorostat_studytask_habitcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
